### ISSUE TITLE
Android 2.3 support

### ISSUE THREAD

**Issue by relan** [ferrannp/material-preferences#16]
I'm trying to make the sample work in Android 2.3 emulator (API 10):

``` patch
diff --git a/sample/build.gradle b/sample/build.gradle
index ce4d69c..159b023 100644
--- a/sample/build.gradle
+++ b/sample/build.gradle
@@ -6,7 +6,7 @@ android {

     defaultConfig {
         applicationId "com.fnp.materialpreferences"
-        minSdkVersion 11
+        minSdkVersion 7
         targetSdkVersion Integer.parseInt(ANDROID_BUILD_TARGET_SDK_VERSION)
         versionCode Integer.parseInt(VERSION_CODE)
         versionName VERSION_NAME
```

This does not work:

```
I/ActivityManager(  802): Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.fnp.materialpreferences/com.fnp.materialpreferencessample.SettingsActivity } from pid 894
I/ActivityManager(  802): Start proc com.fnp.materialpreferences for activity com.fnp.materialpreferences/com.fnp.materialpreferencessample.SettingsActivity: pid=2356 uid=10034 gids={}
W/dalvikvm( 2356): Unable to resolve superclass of Lcom/fnp/materialpreferences/PreferenceFragment; (211)
W/dalvikvm( 2356): Link of class 'Lcom/fnp/materialpreferences/PreferenceFragment;' failed
W/dalvikvm( 2356): Unable to resolve superclass of Lcom/fnp/materialpreferencessample/SettingsActivity$MyPreferenceFragment; (1782)
W/dalvikvm( 2356): Link of class 'Lcom/fnp/materialpreferencessample/SettingsActivity$MyPreferenceFragment;' failed
E/dalvikvm( 2356): Could not find class 'com.fnp.materialpreferencessample.SettingsActivity$MyPreferenceFragment', referenced from method com.fnp.materialpreferencessample.SettingsActivity.onCreate
W/dalvikvm( 2356): VFY: unable to resolve new-instance 1813 (Lcom/fnp/materialpreferencessample/SettingsActivity$MyPreferenceFragment;) in Lcom/fnp/materialpreferencessample/SettingsActivity;
D/dalvikvm( 2356): VFY: replacing opcode 0x22 at 0x0003
D/dalvikvm( 2356): VFY: dead code 0x0005-000b in Lcom/fnp/materialpreferencessample/SettingsActivity;.onCreate (Landroid/os/Bundle;)V
I/dalvikvm( 2356): Could not find method com.fnp.materialpreferences.PreferenceActivity.getFragmentManager, referenced from method com.fnp.materialpreferences.PreferenceActivity.onOptionsItemSelected
W/dalvikvm( 2356): VFY: unable to resolve virtual method 14839: Lcom/fnp/materialpreferences/PreferenceActivity;.getFragmentManager ()Landroid/app/FragmentManager;
D/dalvikvm( 2356): VFY: replacing opcode 0x6e at 0x0012
D/dalvikvm( 2356): VFY: dead code 0x0015-0022 in Lcom/fnp/materialpreferences/PreferenceActivity;.onOptionsItemSelected (Landroid/view/MenuItem;)Z
W/dalvikvm( 2356): Unable to resolve superclass of Lcom/fnp/materialpreferences/PreferenceFragment; (211)
W/dalvikvm( 2356): Link of class 'Lcom/fnp/materialpreferences/PreferenceFragment;' failed
W/dalvikvm( 2356): VFY: unable to find class referenced in signature (Lcom/fnp/materialpreferences/PreferenceFragment;)
I/dalvikvm( 2356): Could not find method com.fnp.materialpreferences.PreferenceActivity.getFragmentManager, referenced from method com.fnp.materialpreferences.PreferenceActivity.setPreferenceFragment
W/dalvikvm( 2356): VFY: unable to resolve virtual method 14839: Lcom/fnp/materialpreferences/PreferenceActivity;.getFragmentManager ()Landroid/app/FragmentManager;
D/dalvikvm( 2356): VFY: replacing opcode 0x6e at 0x0000
D/dalvikvm( 2356): VFY: dead code 0x0003-002e in Lcom/fnp/materialpreferences/PreferenceActivity;.setPreferenceFragment (Lcom/fnp/materialpreferences/PreferenceFragment;)V
I/dalvikvm( 2356): Could not find method android.view.Window.hasFeature, referenced from method android.support.v7.app.AppCompatDelegateImplV7.hasWindowFeature
W/dalvikvm( 2356): VFY: unable to resolve virtual method 14100: Landroid/view/Window;.hasFeature (I)Z
D/dalvikvm( 2356): VFY: replacing opcode 0x6e at 0x0009
D/dalvikvm( 2356): VFY: dead code 0x000c-000c in Landroid/support/v7/app/AppCompatDelegateImplV7;.hasWindowFeature (I)Z
I/dalvikvm( 2356): Could not find method android.view.Window$Callback.dispatchGenericMotionEvent, referenced from method android.support.v7.internal.view.WindowCallbackWrapper.dispatchGenericMotionEvent
W/dalvikvm( 2356): VFY: unable to resolve interface method 14072: Landroid/view/Window$Callback;.dispatchGenericMotionEvent (Landroid/view/MotionEvent;)Z
D/dalvikvm( 2356): VFY: replacing opcode 0x72 at 0x0002
D/dalvikvm( 2356): VFY: dead code 0x0005-0006 in Landroid/support/v7/internal/view/WindowCallbackWrapper;.dispatchGenericMotionEvent (Landroid/view/MotionEvent;)Z
I/dalvikvm( 2356): Could not find method android.view.Window$Callback.dispatchKeyShortcutEvent, referenced from method android.support.v7.internal.view.WindowCallbackWrapper.dispatchKeyShortcutEvent
W/dalvikvm( 2356): VFY: unable to resolve interface method 14074: Landroid/view/Window$Callback;.dispatchKeyShortcutEvent (Landroid/view/KeyEvent;)Z
D/dalvikvm( 2356): VFY: replacing opcode 0x72 at 0x0002
D/dalvikvm( 2356): VFY: dead code 0x0005-0006 in Landroid/support/v7/internal/view/WindowCallbackWrapper;.dispatchKeyShortcutEvent (Landroid/view/KeyEvent;)Z
W/dalvikvm( 2356): VFY: unable to find class referenced in signature (Landroid/view/ActionMode;)
I/dalvikvm( 2356): Could not find method android.view.Window$Callback.onActionModeFinished, referenced from method android.support.v7.internal.view.WindowCallbackWrapper.onActionModeFinished
W/dalvikvm( 2356): VFY: unable to resolve interface method 14078: Landroid/view/Window$Callback;.onActionModeFinished (Landroid/view/ActionMode;)V
D/dalvikvm( 2356): VFY: replacing opcode 0x72 at 0x0002
D/dalvikvm( 2356): VFY: dead code 0x0005-0005 in Landroid/support/v7/internal/view/WindowCallbackWrapper;.onActionModeFinished (Landroid/view/ActionMode;)V
W/dalvikvm( 2356): VFY: unable to find class referenced in signature (Landroid/view/ActionMode;)
I/dalvikvm( 2356): Could not find method android.view.Window$Callback.onActionModeStarted, referenced from method android.support.v7.internal.view.WindowCallbackWrapper.onActionModeStarted
W/dalvikvm( 2356): VFY: unable to resolve interface method 14079: Landroid/view/Window$Callback;.onActionModeStarted (Landroid/view/ActionMode;)V
D/dalvikvm( 2356): VFY: replacing opcode 0x72 at 0x0002
D/dalvikvm( 2356): VFY: dead code 0x0005-0005 in Landroid/support/v7/internal/view/WindowCallbackWrapper;.onActionModeStarted (Landroid/view/ActionMode;)V
W/dalvikvm( 2356): VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
I/dalvikvm( 2356): Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.internal.view.WindowCallbackWrapper.onSearchRequested
W/dalvikvm( 2356): VFY: unable to resolve interface method 14090: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
D/dalvikvm( 2356): VFY: replacing opcode 0x72 at 0x0002
D/dalvikvm( 2356): VFY: dead code 0x0005-0006 in Landroid/support/v7/internal/view/WindowCallbackWrapper;.onSearchRequested (Landroid/view/SearchEvent;)Z
I/dalvikvm( 2356): Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.internal.view.WindowCallbackWrapper.onWindowStartingActionMode
W/dalvikvm( 2356): VFY: unable to resolve interface method 14093: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;)Landroid/view/ActionMode;
D/dalvikvm( 2356): VFY: replacing opcode 0x72 at 0x0002
D/dalvikvm( 2356): VFY: dead code 0x0005-0006 in Landroid/support/v7/internal/view/WindowCallbackWrapper;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;)Landroid/view/ActionMode;
I/dalvikvm( 2356): Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.internal.view.WindowCallbackWrapper.onWindowStartingActionMode
W/dalvikvm( 2356): VFY: unable to resolve interface method 14094: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
D/dalvikvm( 2356): VFY: replacing opcode 0x72 at 0x0002
D/dalvikvm( 2356): VFY: dead code 0x0005-0006 in Landroid/support/v7/internal/view/WindowCallbackWrapper;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
I/dalvikvm( 2356): Could not find method android.view.ViewGroup.onHoverEvent, referenced from method android.support.v7.widget.Toolbar.onHoverEvent
W/dalvikvm( 2356): VFY: unable to resolve virtual method 13982: Landroid/view/ViewGroup;.onHoverEvent (Landroid/view/MotionEvent;)Z
D/dalvikvm( 2356): VFY: replacing opcode 0x6f at 0x0010
D/dalvikvm( 2356): VFY: dead code 0x0013-0019 in Landroid/support/v7/widget/Toolbar;.onHoverEvent (Landroid/view/MotionEvent;)Z
I/dalvikvm( 2356): Could not find method android.view.ViewGroup.onRtlPropertiesChanged, referenced from method android.support.v7.widget.Toolbar.onRtlPropertiesChanged
W/dalvikvm( 2356): VFY: unable to resolve virtual method 13991: Landroid/view/ViewGroup;.onRtlPropertiesChanged (I)V
D/dalvikvm( 2356): VFY: replacing opcode 0x6f at 0x0007
I/dalvikvm( 2356): Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.internal.widget.TintTypedArray.getChangingConfigurations
W/dalvikvm( 2356): VFY: unable to resolve virtual method 411: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
D/dalvikvm( 2356): VFY: replacing opcode 0x6e at 0x0002
D/dalvikvm( 2356): VFY: dead code 0x0005-0006 in Landroid/support/v7/internal/widget/TintTypedArray;.getChangingConfigurations ()I
I/dalvikvm( 2356): Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.internal.widget.TintTypedArray.getType
W/dalvikvm( 2356): VFY: unable to resolve virtual method 433: Landroid/content/res/TypedArray;.getType (I)I
D/dalvikvm( 2356): VFY: replacing opcode 0x6e at 0x0002
D/dalvikvm( 2356): VFY: dead code 0x0005-0006 in Landroid/support/v7/internal/widget/TintTypedArray;.getType (I)I
D/AndroidRuntime( 2356): Shutting down VM
W/dalvikvm( 2356): threadid=1: thread exiting with uncaught exception (group=0xb6f7f4f0)
E/AndroidRuntime( 2356): FATAL EXCEPTION: main
E/AndroidRuntime( 2356): java.lang.NoClassDefFoundError: com.fnp.materialpreferencessample.SettingsActivity$MyPreferenceFragment
E/AndroidRuntime( 2356):    at com.fnp.materialpreferencessample.SettingsActivity.onCreate(SettingsActivity.java:11)
E/AndroidRuntime( 2356):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
E/AndroidRuntime( 2356):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1611)
E/AndroidRuntime( 2356):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
E/AndroidRuntime( 2356):    at android.app.ActivityThread.access$1500(ActivityThread.java:117)
E/AndroidRuntime( 2356):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
E/AndroidRuntime( 2356):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 2356):    at android.os.Looper.loop(Looper.java:130)
E/AndroidRuntime( 2356):    at android.app.ActivityThread.main(ActivityThread.java:3683)
E/AndroidRuntime( 2356):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2356):    at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime( 2356):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
E/AndroidRuntime( 2356):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 2356):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  802):   Force finishing activity com.fnp.materialpreferences/com.fnp.materialpreferencessample.SettingsActivity
```

The problem is that `PreferenceFragment` exists only for API 11+:

``` java
@TargetApi(Build.VERSION_CODES.HONEYCOMB)
public abstract class PreferenceFragment extends android.preference.PreferenceFragment {
...
```

That's quite confusing because README states that library supports API 7. Are pre-Honecomb versions really supported or this is a typo?

**Comment by ferrannp** [comment]
You are right. It is a typo. Before API 11 there are no fragments... I'd need to investigate if we can reuse this code to make it work before 11 (and write a sample-v7), maybe PR? :)
