### ISSUE TITLE
Crashed on lollipop

### ISSUE THREAD

**Issue by Lir10** [ferrannp/material-preferences#4]
im launching SettingsActivity from ActionBarActivity with intent like this : 

 Intent settings= new Intent(SampleActivity.this,SettingsActivity.class);
 startActivity(settings);

Logcat:

``` javascript
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ye.ok.SettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setHomeButtonEnabled(boolean)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setHomeButtonEnabled(boolean)' on a null object reference
at com.fnp.materialpreferences.PreferenceActivity.onCreate(PreferenceActivity.java:44)
at com.xorcom.amity.amityappdemo.SettingsActivity.onCreate(SettingsActivity.java:17)
at android.app.Activity.performCreate(Activity.java:5990)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
... 10 more
```

**Comment by ferrannp** [comment]
I'll take a look :)

**Comment by ferrannp** [comment]
Was this a Lollipop device? Looks like your activity has no action bar... The library just adds a manual toolbar for pre-Lollipop devices. For Lollipop or above, you have to handle it by yourself. Basically, don't  set `windowActionBar="false"`in your styles file. Take a look at:

https://github.com/ferrannp/material-preferences/blob/master/sample/src/main/res/values-v21/styles.xml#L4

Which overrides the style from:

https://github.com/ferrannp/material-preferences/blob/master/sample/src/main/res/values/styles.xml#L17
